target-version = "py313"
line-length = 88
extend-exclude = ["migrations", "__pycache__", ".venv", "env"]

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[format]
quote-style = "double"
indent-style = "space"
